### PR TITLE
add english language

### PR DESCRIPTION
**Pull request by Kylescottw**
English users can now reference the english language in the _config.yml

### CODE REVIEW

**Comment by NoahDragon** [comment]
The English is in the default.yml. https://github.com/hexojs/hexo-theme-landscape/blob/master/languages/default.yml

**Comment by Kylescottw** [comment]
Hi Noah, I was referencing the default in the _config.yml but the blog was not changing my language, only after creating a en.yml and referencing it in the _config was I able to get the English working properly.

**Comment by Kylescottw** [comment]
Hi Noah,
It seems that when hexo create new blog is initialized for the first time.
The language is french rather than the default.

**Comment by NoahDragon** [comment]
Yes, I also encountered such scenario. However, if you set the language to en, it will use the default one.

**Pull request closed without merging**
