### PR TITLE
chore: bump to CDN jQuery from 2.0.3 to 3.4.1

### PR DESCRIPTION
**Pull request by YoshinoriN**

### CODE REVIEW

**Comment by weyusi** [comment]
jsDelivr has [good coverage](https://www.jsdelivr.com/network#china) in China. Since hexo has many chinese users, may I suggest to switch to it?
It is also possible to specify a major version (`https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js`), which works like npm `"jquery": "^3.4.1"`.

fancybox and fontawesome could also be CDN-ed, maybe consider after https://github.com/hexojs/hexo-theme-landscape/pull/126.

**Comment by YoshinoriN** [comment]
@weyusi 
I think it's a good idea ;)
I add commit to change jsDeliver CDN.

**Comment by tomap** [comment]
Does the theme still work?
Did someone tested it? on various browser (IE, Chrome & Firefox at least)

**Comment by weyusi** [comment]
Just found an issue with IE11
Link | Status
--- | ---
//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js | Works
//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js | No
//cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js | No
/js/jquery.v3.4.1.min.js | Works

https://stackoverflow.com/questions/20214242/jquery-is-undefined-exception-in-ie11
https://stackoverflow.com/questions/40178845/ie11-jquery-error

To fix it, add
```html
<script>
window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')
</script>
```

and the jquery.min.js file to source/js/.

**Comment by YoshinoriN** [comment]
Thanks @curbengh !

I think we should self-host it. Because, it seems other (e.g. fontawesome, fancybox) resources will be self-host #126 & as say @curbengh  IE11 will work if self-host.

I will close once & re-create PR after merge #126 If there is no opposite opinion.

@tomap 

> Does the theme still work?

Your point out is `theme` or `this PR`? Maybe no problem if that specified theme. Because sometimes I use this theme for investigate issue in my [repository](https://github.com/YoshinoriN/hexo-test) :)

**Comment by curbengh** [comment]
self-host is fine, users who prefer CDN can easily modify the theme.
btw, could you also replace '<script src>` with `<%- js() %>`? dogfooding 😆

**Comment by curbengh** [comment]
@YoshinoriN 
any update?

**Comment by YoshinoriN** [comment]
@curbengh 
Sorry, I forgot this PR. I create another PR #142

**Pull request closed without merging**
