### PR TITLE
Improved sidebar behavior

### PR DESCRIPTION
**Pull request by ideoplex**
1. Expose show_count on article, category, tag widgets as theme.show_count.
1. Expose archive_type on archive widget as theme.archive_type
2. When sidebar is on the bottom:
    1. Make the widgets full width
    2. Make the lists run horizontally

### CODE REVIEW

**Comment by Xuanwo** [comment]
@ideoplex to keep the same with old version, will it better to make `show_count` false as default?

**Comment by ideoplex** [comment]
@Xuanwo Yes I think it would be better to make show_count false as default.

I'm a bit new to git. I thought that I was only including my updates from 2014 in my pull request, but it looks like my changes from November 2015 are included. The November 2015 changes are working for me, but I don't think they're ready for the general public yet.

**Comment by Xuanwo** [comment]
@ideoplex Maybe you can create a new branch that track on this repo and made this change

**Comment by ideoplex** [comment]
@Xuanwo - I created a new [tracking](https://github.com/ideoplex/hexo-theme-landscape/tree/tracking) branch. How would you like to proceed from here? Should we close this request and create a new one?

**Comment by Xuanwo** [comment]
set upsteam as git@github.com:hexojs/hexo-theme-landscape.git & rebase your code to undo all of your changes, then do the `Improved sidebar behavior`. And do those work in a new branch to prevent losing your work before.

**Comment by Xuanwo** [comment]
Well, I learn git again, and I'm trying to fix this conflict.

**Comment by Xuanwo** [comment]
@ideoplex , I made `show_count` defaults as `false` to keep the same with old version, and remove the changes in `footer.ejs` because not everyone write blog from 2003, :smile: .

**Comment by stevenjoezhang** [comment]
I apologize for replying to this thread from ten years ago. I noticed that `index_widgets` was added in one of the commits, but the related code was not included when it was ultimately merged. I will temporarily remove this configuration option. Please consider re-adding it if necessary. Thank you.

**Pull request merged**
