### PR TITLE
Add RU language and translation constant includes

### PR DESCRIPTION
**Pull request by taur-firiath**

### CODE REVIEW

**Comment by Xuanwo** [comment]
Can you split them in different pull request?
So that we can have a discussion on should we change the code in layout.

**Comment by taur-firiath** [comment]
Into how many parts I have to divide the pull request? And that should include every part?

**Comment by Xuanwo** [comment]
And it looks like we need to do some work for zh-CN

**Comment by taur-firiath** [comment]
Just translate *newer*, *older*, *share*, *powered_by*, *rss_feed*, *category*, *tag* constants.
It needs in *no.yml*, *zh-CN.yml* and *zh-TW.yml*.

**Comment by Xuanwo** [comment]
I got it.

**Pull request merged**
