### PR TITLE
Fixed data URL bug with share button

### PR DESCRIPTION
**Pull request by Octo8080**
Fixed a problem that generated URL is wrong when operating in subdirectory.
Before modification, the setting value at root  of _confi.yml root was ignored.

### CODE REVIEW

**Comment by tomap** [comment]
You are transforming a relative url into an absolute url. I believe config.root+post.path should be enough.

**Comment by Octo8080** [comment]
Thanks for your suggestion(I believe config.root+post.path should be enough. ).
However, I think that there is a problem with config.root + post.path.
For example, if you create a post on twitter with a relative URL, you use root / 2018/08/24 / hello-world /. This URL is not valid.
I believe that the URL to be placed on the share button needs to be an absolute URL.

**Comment by tcrowe** [comment]
Hey guys :wave: Thanks for giving some ideas for this. I know we're taking a while to get to items since we have so many issues. If you can help close out issues that will be great.

For this type of thing we would want to go the route of using helpers like `url_for:
https://hexo.io/docs/helpers#url-for

**Comment by curbengh** [comment]
`root:` value should also be included in `url:` in your _config.yml.
See

https://github.com/hexojs/hexo-starter/blob/571320ba41a83e065d7560e050eb3fa63ad74a57/_config.yml#L15 

https://github.com/hexojs/hexo/pull/3604#issuecomment-511323247

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo-util/pull/84 has been merged.

Pending new version of hexo-util and `full_url_for()` helper.

**Pull request closed without merging**
