### PR TITLE
chore: Bump jQuery 2.0.3 to 3.4.1 & self-host & use js tag helper 

### PR DESCRIPTION
**Pull request by YoshinoriN**
## Description

From #139 

* Migrate jquery 2.0.3 to 3.4.1
* self-host instead of CDN
* use js taghelper `<%- js(' ')>`

jQuery [3.4-stable branch](https://github.com/jquery/jquery/tree/3.4-stable) does not have a build artifact.
I add jquery dependency & copy it instead of `gitclone`.

## Test

**grunt default**

```
$ grunt default

Running "gitclone:fontawesome" (gitclone) task

Running "gitclone:fancybox" (gitclone) task

Running "copy:fontawesome" (copy) task
Copied 6 files

Running "copy:fancybox" (copy) task
Created 1 directory, copied 15 files

Running "copy:jquery" (copy) task
Copied 1 file

Running "_clean:tmp" (_clean) task
>> 1 path cleaned.

Done.
```

**grunt jquery**

```
$ grunt jquery

Running "copy:jquery" (copy) task
Copied 1 file

Done.
```

**grunt clean**

```
$ grunt clean

Running "_clean:tmp" (_clean) task
>> 1 path cleaned.

Running "_clean:fontawesome" (_clean) task
>> 1 path cleaned.

Running "_clean:fancybox" (_clean) task
>> 1 path cleaned.

Running "_clean:jquery" (_clean) task
>> 1 path cleaned.

Done.
```

### Screenshot

jquery

### CODE REVIEW

**Comment by curbengh** [comment]
I can verify the hash of jquery.min.js correspond to https://code.jquery.com/jquery-3.4.1.min.js.

I'm not in favor in adding jquery npm though, because it installs a bunch of files, even though we only need jquery.min.js.

**Comment by curbengh** [comment]
I can accept jquery npm, but it should be a devDependency because users are not expected to install it (since this repo already bundles it).

**Comment by YoshinoriN** [comment]
@curbengh 
Thanks. I think first review is better (non-used gulp for jquery). I will update later :)

Anyways the Grunt task is really needed? I don't think so. I don't know & I can't come up with why @tommy351 added it.

I'm not familiar with Grunt. But it seems just do git clone & copy it. We already added fontawesome & fancybox in source directory. 

So, IMO the Grunt task has already no need and we might as well delete. How do you think?

I will create another PR, If delete Grunt  ;)

**Comment by curbengh** [comment]
We are on the same page, I also think Grunt is not useful in this case.

**Comment by YoshinoriN** [comment]
Thanks :)
I delete grunt task for jquery. And create another PR for delete Grunt #143

**Pull request merged**
